#!/usr/bin/env bash
SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

# Set arguments as Docker options ($@)
echo docker run $@ -it --rm --name zookeeper --network my_network -p 2181:2181 -p 2888:2888 -p 3888:3888 debezium/zookeeper:2.4
docker run $@ -it --rm --name zookeeper --network my_network -p 2181:2181 -p 2888:2888 -p 3888:3888 debezium/zookeeper:2.4
