#!/usr/bin/env bash
SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

# Set arguments as Docker options ($@)
echo docker run $@ -it --rm --name kafka --network my_network -p 9092:9092 -e ZOOKEEPER_CONNECT=zookeeper quay.io/debezium/kafka:2.4
docker run $@ -it --rm --name kafka --network my_network -p 9092:9092 -e ZOOKEEPER_CONNECT=zookeeper quay.io/debezium/kafka:2.4
