#!/usr/bin/env bash
SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

# Set arguments as Docker options ($@)
echo docker run $@ -it --rm --name kafka --network my_network ZOOKEEPER_CONNECT=zookeeper -p 9092:9092 padogrid/debezium-kafka-openjdk8:latest
docker run $@ -it --rm --name kafka --network my_network -e ZOOKEEPER_CONNECT=zookeeper -p 9092:9092 padogrid/debezium-kafka-openjdk8:latest
