#!/usr/bin/env bash
SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

#docker run -it --rm --name mysqlterm --network my_network mysql:5.7 sh -c 'exec mysql -hmysql -P3306 -uroot -pdebezium'
docker run -it --rm --name mysqlterm --network my_network mysql:8.3 sh -c 'exec mysql -hmysql -P3306 -uroot -pdebezium'

